import { FormEvent, useEffect, useState } from 'react';
import { alertApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { Alert, AlertSeverity, AlertStatus, AlertType } from '../types';
import { formatDateTime } from '../utils/format';

const initialForm = { device_id: '', alert_type: 'other' as AlertType, severity: 'low' as AlertSeverity, title: '', description: '', status: 'open' as AlertStatus };
export default function AlertsPage() {
  const [items, setItems] = useState<Alert[]>([]); const [form, setForm] = useState(initialForm); const [error, setError] = useState('');
  const loadData = () => alertApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { await alertApi.create({ ...form, device_id: form.device_id ? Number(form.device_id) : null, description: form.description || null }); setForm(initialForm); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Create failed'); } };
  const acknowledge = async (id: number) => { try { await alertApi.acknowledge(id); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Action failed'); } };
  const resolve = async (id: number) => { try { await alertApi.resolve(id); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Action failed'); } };
  return <div><PageHeader title="Alerts" subtitle="Monitor unresolved issues and update alert status." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>Create alert</h3><label>Device ID<input value={form.device_id} onChange={(e) => setForm({ ...form, device_id: e.target.value })} /></label><label>Type<select value={form.alert_type} onChange={(e) => setForm({ ...form, alert_type: e.target.value as AlertType })}><option value="gas">Gas</option><option value="device_offline">Device offline</option><option value="plate_mismatch">Plate mismatch</option><option value="barrier_error">Barrier error</option><option value="unauthorized_access">Unauthorized access</option><option value="other">Other</option></select></label><label>Severity<select value={form.severity} onChange={(e) => setForm({ ...form, severity: e.target.value as AlertSeverity })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as AlertStatus })}><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option></select></label><label className="span-2">Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label className="span-2">Description<input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="button">Create alert</button></form><section className="card"><table><thead><tr><th>Title</th><th>Type</th><th>Severity</th><th>Status</th><th>Detected</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.alert_id}><td>{item.title}</td><td>{item.alert_type}</td><td><StatusBadge value={item.severity} /></td><td><StatusBadge value={item.status} /></td><td>{formatDateTime(item.detected_at)}</td><td className="actions"><button className="button small secondary" onClick={() => acknowledge(item.alert_id)}>Acknowledge</button><button className="button small danger" onClick={() => resolve(item.alert_id)}>Resolve</button></td></tr>)}</tbody></table></section></div></div>;
}
