import { FormEvent, useEffect, useState } from 'react';
import { paymentApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { Payment, PaymentMethod, PaymentRecordStatus } from '../types';
import { formatDateTime, formatMoney } from '../utils/format';

const initialForm = { payment_type: 'single', session_id: '', subscription_id: '', customer_id: '', amount: '', payment_method: 'cash' as PaymentMethod, status: 'paid' as PaymentRecordStatus, paid_at: '', note: '' };
export default function PaymentsPage() {
  const [items, setItems] = useState<Payment[]>([]); const [form, setForm] = useState(initialForm); const [error, setError] = useState('');
  const loadData = () => paymentApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const payload = { ...form, session_id: form.session_id ? Number(form.session_id) : null, subscription_id: form.subscription_id ? Number(form.subscription_id) : null, customer_id: form.customer_id ? Number(form.customer_id) : null, amount: Number(form.amount), paid_at: form.paid_at || null, note: form.note || null }; await paymentApi.create(payload); setForm(initialForm); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Create failed'); } };
  return <div><PageHeader title="Payments" subtitle="Record payments and monitor recent transactions." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>Create payment</h3><label>Payment type<select value={form.payment_type} onChange={(e) => setForm({ ...form, payment_type: e.target.value })}><option value="single">Single</option><option value="monthly">Monthly</option></select></label><label>Session ID<input value={form.session_id} onChange={(e) => setForm({ ...form, session_id: e.target.value })} /></label><label>Subscription ID<input value={form.subscription_id} onChange={(e) => setForm({ ...form, subscription_id: e.target.value })} /></label><label>Customer ID<input value={form.customer_id} onChange={(e) => setForm({ ...form, customer_id: e.target.value })} /></label><label>Amount<input type="number" min="0" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required /></label><label>Method<select value={form.payment_method} onChange={(e) => setForm({ ...form, payment_method: e.target.value as PaymentMethod })}><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="e_wallet">E-wallet</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as PaymentRecordStatus })}><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></label><label>Paid at<input type="datetime-local" value={form.paid_at} onChange={(e) => setForm({ ...form, paid_at: e.target.value })} /></label><label className="span-2">Note<input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="button">Create payment</button></form><section className="card"><table><thead><tr><th>Code</th><th>Amount</th><th>Method</th><th>Status</th><th>Paid at</th></tr></thead><tbody>{items.map((item) => <tr key={item.payment_id}><td>{item.payment_code}</td><td>{formatMoney(item.amount)}</td><td>{item.payment_method}</td><td><StatusBadge value={item.status} /></td><td>{formatDateTime(item.paid_at)}</td></tr>)}</tbody></table></section></div></div>;
}
