import { FormEvent, useEffect, useState } from 'react';
import { planApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { MonthlyPlan, UserStatus, VehicleType } from '../types';
import { formatMoney } from '../utils/format';

const initialForm = { plan_name: '', vehicle_type: 'motorbike' as VehicleType, duration_months: 1, price: '', description: '', status: 'active' as UserStatus };
export default function PlansPage() {
  const [items, setItems] = useState<MonthlyPlan[]>([]); const [form, setForm] = useState(initialForm); const [editingId, setEditingId] = useState<number | null>(null); const [error, setError] = useState('');
  const loadData = () => planApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const payload = { ...form, price: Number(form.price), description: form.description || null }; editingId ? await planApi.update(editingId, payload) : await planApi.create(payload); setForm(initialForm); setEditingId(null); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Save failed'); } };
  const edit = (item: MonthlyPlan) => {
    setForm({ plan_name: item.plan_name, vehicle_type: item.vehicle_type, duration_months: item.duration_months, price: String(item.price), description: item.description || '', status: item.status as UserStatus });
    setEditingId(item.plan_id);
  };
  const remove = async (id: number) => { if (!confirm('Delete this plan?')) return; try { await planApi.remove(id); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Delete failed'); } };
  return <div><PageHeader title="Monthly Plans" subtitle="Set up recurring parking packages for monthly customers." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>{editingId ? 'Edit plan' : 'Add plan'}</h3><label>Plan name<input value={form.plan_name} onChange={(e) => setForm({ ...form, plan_name: e.target.value })} required /></label><label>Vehicle type<select value={form.vehicle_type} onChange={(e) => setForm({ ...form, vehicle_type: e.target.value as VehicleType })}><option value="motorbike">Motorbike</option><option value="car">Car</option><option value="bicycle">Bicycle</option><option value="truck">Truck</option><option value="other">Other</option></select></label><label>Duration months<input type="number" min="1" value={form.duration_months} onChange={(e) => setForm({ ...form, duration_months: Number(e.target.value) })} required /></label><label>Price<input type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} required /></label><label className="span-2">Description<input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as UserStatus })}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="actions"><button className="button">{editingId ? 'Update' : 'Create'}</button><button type="button" className="button secondary" onClick={() => { setForm(initialForm); setEditingId(null); }}>Clear</button></div></form><section className="card"><table><thead><tr><th>Name</th><th>Type</th><th>Months</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.plan_id}><td>{item.plan_name}</td><td>{item.vehicle_type}</td><td>{item.duration_months}</td><td>{formatMoney(item.price)}</td><td><StatusBadge value={String(item.status)} /></td><td className="actions"><button className="button small secondary" onClick={() => edit(item)}>Edit</button><button className="button small danger" onClick={() => remove(item.plan_id)}>Delete</button></td></tr>)}</tbody></table></section></div></div>;
}
