import { FormEvent, useEffect, useState } from 'react';
import { cardApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { CardStatus, CardType, RFIDCard } from '../types';

const initialForm = { card_uid: '', card_code: '', card_type: 'guest' as CardType, assigned_customer_id: '', assigned_vehicle_id: '', issued_at: '', expired_at: '', status: 'available' as CardStatus, note: '' };
export default function RfidCardsPage() {
  const [items, setItems] = useState<RFIDCard[]>([]); const [form, setForm] = useState(initialForm); const [editingId, setEditingId] = useState<number | null>(null); const [error, setError] = useState('');
  const loadData = () => cardApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const payload = { ...form, card_code: form.card_code || null, assigned_customer_id: form.assigned_customer_id ? Number(form.assigned_customer_id) : null, assigned_vehicle_id: form.assigned_vehicle_id ? Number(form.assigned_vehicle_id) : null, issued_at: form.issued_at || null, expired_at: form.expired_at || null, note: form.note || null }; editingId ? await cardApi.update(editingId, payload) : await cardApi.create(payload); setForm(initialForm); setEditingId(null); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Save failed'); } };
  const edit = (item: RFIDCard) => { setEditingId(item.card_id); setForm({ card_uid: item.card_uid, card_code: item.card_code || '', card_type: item.card_type, assigned_customer_id: item.assigned_customer_id?.toString() || '', assigned_vehicle_id: item.assigned_vehicle_id?.toString() || '', issued_at: item.issued_at ? item.issued_at.slice(0, 16) : '', expired_at: item.expired_at ? item.expired_at.slice(0, 16) : '', status: item.status, note: item.note || '' }); };
  return <div><PageHeader title="RFID Cards" subtitle="Track guest and monthly cards used at the gates." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>{editingId ? 'Edit card' : 'Add card'}</h3><label>Card UID<input value={form.card_uid} onChange={(e) => setForm({ ...form, card_uid: e.target.value })} required disabled={!!editingId} /></label><label>Card code<input value={form.card_code} onChange={(e) => setForm({ ...form, card_code: e.target.value })} /></label><label>Card type<select value={form.card_type} onChange={(e) => setForm({ ...form, card_type: e.target.value as CardType })}><option value="guest">Guest</option><option value="monthly">Monthly</option><option value="staff">Staff</option></select></label><label>Customer ID<input value={form.assigned_customer_id} onChange={(e) => setForm({ ...form, assigned_customer_id: e.target.value })} /></label><label>Vehicle ID<input value={form.assigned_vehicle_id} onChange={(e) => setForm({ ...form, assigned_vehicle_id: e.target.value })} /></label><label>Issued at<input type="datetime-local" value={form.issued_at} onChange={(e) => setForm({ ...form, issued_at: e.target.value })} /></label><label>Expired at<input type="datetime-local" value={form.expired_at} onChange={(e) => setForm({ ...form, expired_at: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as CardStatus })}><option value="available">Available</option><option value="assigned">Assigned</option><option value="lost">Lost</option><option value="blocked">Blocked</option><option value="inactive">Inactive</option></select></label><label className="span-2">Note<input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><div className="actions"><button className="button">{editingId ? 'Update' : 'Create'}</button><button type="button" className="button secondary" onClick={() => { setForm(initialForm); setEditingId(null); }}>Clear</button></div></form><section className="card"><table><thead><tr><th>UID</th><th>Code</th><th>Type</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.card_id}><td>{item.card_uid}</td><td>{item.card_code}</td><td>{item.card_type}</td><td><StatusBadge value={item.status} /></td><td><button className="button small secondary" onClick={() => edit(item)}>Edit</button></td></tr>)}</tbody></table></section></div></div>;
}
