import { FormEvent, useEffect, useState } from 'react';
import { sessionApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { ParkingSession, PaymentMethod } from '../types';
import { formatDateTime, formatMoney } from '../utils/format';

export default function SessionsPage() {
  const [items, setItems] = useState<ParkingSession[]>([]); const [search, setSearch] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [checkIn, setCheckIn] = useState({ card_uid: '', plate_number: '', gate_id: 1, image_url: '' });
  const [checkOut, setCheckOut] = useState({ card_uid: '', plate_number: '', gate_id: 2, image_url: '', payment_method: 'cash' as PaymentMethod });
  const loadData = () => sessionApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submitCheckIn = async (e: FormEvent) => { e.preventDefault(); try { const res = await sessionApi.checkIn({ ...checkIn, image_url: checkIn.image_url || undefined }); setMessage(res.message); setCheckIn({ card_uid: '', plate_number: '', gate_id: 1, image_url: '' }); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Check-in failed'); } };
  const submitCheckOut = async (e: FormEvent) => { e.preventDefault(); try { const res = await sessionApi.checkOut({ ...checkOut, image_url: checkOut.image_url || undefined }); setMessage(res.message); setCheckOut({ card_uid: '', plate_number: '', gate_id: 2, image_url: '', payment_method: 'cash' }); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Check-out failed'); } };
  const searchPlate = async () => { try { setError(''); setItems(search ? await sessionApi.searchByPlate(search) : await sessionApi.list()); } catch (err) { setError(err instanceof Error ? err.message : 'Search failed'); } };
  return <div><PageHeader title="Parking Sessions" subtitle="Operate check-in / check-out and review parking history." />{message ? <div className="alert success">{message}</div> : null}{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submitCheckIn}><h3>Check-in</h3><label>Card UID<input value={checkIn.card_uid} onChange={(e) => setCheckIn({ ...checkIn, card_uid: e.target.value })} required /></label><label>Plate number<input value={checkIn.plate_number} onChange={(e) => setCheckIn({ ...checkIn, plate_number: e.target.value })} required /></label><label>Gate ID<input type="number" value={checkIn.gate_id} onChange={(e) => setCheckIn({ ...checkIn, gate_id: Number(e.target.value) })} required /></label><label>Image URL<input value={checkIn.image_url} onChange={(e) => setCheckIn({ ...checkIn, image_url: e.target.value })} /></label><button className="button">Check in</button></form><form className="card form-grid" onSubmit={submitCheckOut}><h3>Check-out</h3><label>Card UID<input value={checkOut.card_uid} onChange={(e) => setCheckOut({ ...checkOut, card_uid: e.target.value })} required /></label><label>Plate number<input value={checkOut.plate_number} onChange={(e) => setCheckOut({ ...checkOut, plate_number: e.target.value })} required /></label><label>Gate ID<input type="number" value={checkOut.gate_id} onChange={(e) => setCheckOut({ ...checkOut, gate_id: Number(e.target.value) })} required /></label><label>Image URL<input value={checkOut.image_url} onChange={(e) => setCheckOut({ ...checkOut, image_url: e.target.value })} /></label><label>Payment method<select value={checkOut.payment_method} onChange={(e) => setCheckOut({ ...checkOut, payment_method: e.target.value as PaymentMethod })}><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="e_wallet">E-wallet</option></select></label><button className="button">Check out</button></form></div><section className="card"><div className="toolbar"><input placeholder="Search by plate number" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="button secondary" onClick={searchPlate}>Search</button><button className="button secondary" onClick={loadData}>Refresh</button></div><table><thead><tr><th>Code</th><th>Plate</th><th>Status</th><th>Payment</th><th>Entry</th><th>Exit</th><th>Fee</th></tr></thead><tbody>{items.map((item) => <tr key={item.session_id}><td>{item.session_code}</td><td>{item.entry_plate_number}</td><td><StatusBadge value={item.session_status} /></td><td><StatusBadge value={item.payment_status} /></td><td>{formatDateTime(item.entry_time)}</td><td>{formatDateTime(item.exit_time)}</td><td>{formatMoney(item.parking_fee)}</td></tr>)}</tbody></table></section></div>;
}
