import { FormEvent, useEffect, useState } from 'react';
import { subscriptionApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { MonthlySubscription, SubscriptionStatus } from '../types';
import { formatMoney } from '../utils/format';

const initialForm = { plan_id: '', customer_id: '', vehicle_id: '', card_id: '', start_date: '', end_date: '', registered_price: '', status: 'active' as SubscriptionStatus };
export default function SubscriptionsPage() {
  const [items, setItems] = useState<MonthlySubscription[]>([]); const [form, setForm] = useState(initialForm); const [editingId, setEditingId] = useState<number | null>(null); const [error, setError] = useState('');
  const loadData = () => subscriptionApi.list().then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const payload = { ...form, plan_id: Number(form.plan_id), customer_id: Number(form.customer_id), vehicle_id: Number(form.vehicle_id), card_id: form.card_id ? Number(form.card_id) : null, registered_price: Number(form.registered_price) }; editingId ? await subscriptionApi.update(editingId, payload) : await subscriptionApi.create(payload); setForm(initialForm); setEditingId(null); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Save failed'); } };
  const edit = (item: MonthlySubscription) => { setEditingId(item.subscription_id); setForm({ plan_id: String(item.plan_id), customer_id: String(item.customer_id), vehicle_id: String(item.vehicle_id), card_id: item.card_id?.toString() || '', start_date: item.start_date, end_date: item.end_date, registered_price: String(item.registered_price), status: item.status }); };
  const remove = async (id: number) => { if (!confirm('Delete this subscription?')) return; try { await subscriptionApi.remove(id); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Delete failed'); } };
  return <div><PageHeader title="Monthly Subscriptions" subtitle="Connect plans, customers, vehicles, and RFID cards together." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>{editingId ? 'Edit subscription' : 'Add subscription'}</h3><label>Plan ID<input value={form.plan_id} onChange={(e) => setForm({ ...form, plan_id: e.target.value })} required /></label><label>Customer ID<input value={form.customer_id} onChange={(e) => setForm({ ...form, customer_id: e.target.value })} required /></label><label>Vehicle ID<input value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })} required /></label><label>Card ID<input value={form.card_id} onChange={(e) => setForm({ ...form, card_id: e.target.value })} /></label><label>Start date<input type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} required /></label><label>End date<input type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} required /></label><label>Registered price<input type="number" min="0" value={form.registered_price} onChange={(e) => setForm({ ...form, registered_price: e.target.value })} required /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as SubscriptionStatus })}><option value="active">Active</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label><div className="actions"><button className="button">{editingId ? 'Update' : 'Create'}</button><button type="button" className="button secondary" onClick={() => { setForm(initialForm); setEditingId(null); }}>Clear</button></div></form><section className="card"><table><thead><tr><th>ID</th><th>Plan</th><th>Customer</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.subscription_id}><td>{item.subscription_id}</td><td>{item.plan_id}</td><td>{item.customer_id}</td><td>{formatMoney(item.registered_price)}</td><td><StatusBadge value={item.status} /></td><td className="actions"><button className="button small secondary" onClick={() => edit(item)}>Edit</button><button className="button small danger" onClick={() => remove(item.subscription_id)}>Delete</button></td></tr>)}</tbody></table></section></div></div>;
}
