import { FormEvent, useEffect, useState } from 'react';
import { vehicleApi } from '../api/services';
import PageHeader from '../components/PageHeader';
import StatusBadge from '../components/StatusBadge';
import type { UserStatus, Vehicle, VehicleType } from '../types';

const initialForm = { customer_id: '', plate_number: '', vehicle_type: 'motorbike' as VehicleType, brand: '', model: '', color: '', status: 'active' as UserStatus };
export default function VehiclesPage() {
  const [items, setItems] = useState<Vehicle[]>([]); const [form, setForm] = useState(initialForm); const [editingId, setEditingId] = useState<number | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const loadData = () => vehicleApi.list(search).then(setItems).catch((e) => setError(e.message));
  useEffect(() => { loadData(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); try { const payload = { ...form, customer_id: form.customer_id ? Number(form.customer_id) : null, brand: form.brand || null, model: form.model || null, color: form.color || null }; editingId ? await vehicleApi.update(editingId, payload) : await vehicleApi.create(payload); setForm(initialForm); setEditingId(null); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Save failed'); } };
  const edit = (item: Vehicle) => { setEditingId(item.vehicle_id); setForm({ customer_id: item.customer_id?.toString() || '', plate_number: item.plate_number, vehicle_type: item.vehicle_type, brand: item.brand || '', model: item.model || '', color: item.color || '', status: (item.status as UserStatus) || 'active' }); };
  const remove = async (id: number) => { if (!confirm('Delete this vehicle?')) return; try { await vehicleApi.remove(id); loadData(); } catch (err) { setError(err instanceof Error ? err.message : 'Delete failed'); } };
  return <div><PageHeader title="Vehicles" subtitle="Manage registered vehicles and basic details." />{error ? <div className="alert error">{error}</div> : null}<div className="grid-2"><form className="card form-grid" onSubmit={submit}><h3>{editingId ? 'Edit vehicle' : 'Add vehicle'}</h3><label>Customer ID<input value={form.customer_id} onChange={(e) => setForm({ ...form, customer_id: e.target.value })} /></label><label>Plate number<input value={form.plate_number} onChange={(e) => setForm({ ...form, plate_number: e.target.value })} required /></label><label>Vehicle type<select value={form.vehicle_type} onChange={(e) => setForm({ ...form, vehicle_type: e.target.value as VehicleType })}><option value="motorbike">Motorbike</option><option value="car">Car</option><option value="bicycle">Bicycle</option><option value="truck">Truck</option><option value="other">Other</option></select></label><label>Brand<input value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} /></label><label>Model<input value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /></label><label>Color<input value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as UserStatus })}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="actions"><button className="button">{editingId ? 'Update' : 'Create'}</button><button type="button" className="button secondary" onClick={() => { setForm(initialForm); setEditingId(null); }}>Clear</button></div></form><section className="card"><div className="toolbar"><input placeholder="Search by plate number" value={search} onChange={(e) => setSearch(e.target.value)} /><button className="button secondary" onClick={loadData}>Search</button></div><table><thead><tr><th>Plate</th><th>Type</th><th>Customer</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.vehicle_id}><td>{item.plate_number}</td><td>{item.vehicle_type}</td><td>{item.customer_id ?? '-'}</td><td><StatusBadge value={String(item.status)} /></td><td className="actions"><button className="button small secondary" onClick={() => edit(item)}>Edit</button><button className="button small danger" onClick={() => remove(item.vehicle_id)}>Delete</button></td></tr>)}</tbody></table></section></div></div>;
}
