@echo off
setlocal

set ROOT_DIR=%~dp0..
set BACKEND_DIR=%ROOT_DIR%\backend_v3
set FRONTEND_INDEX=%ROOT_DIR%\frontend_v3\index.html

set PYTHON_EXE=python
if exist "C:\Users\Admin\miniconda3\envs\pbl5-ai\python.exe" (
    set PYTHON_EXE=C:\Users\Admin\miniconda3\envs\pbl5-ai\python.exe
) else if exist "%BACKEND_DIR%\.venv-py312\Scripts\python.exe" (
    set PYTHON_EXE=%BACKEND_DIR%\.venv-py312\Scripts\python.exe
)

set ENABLE_DEV_ACCESS_TOOLS=false
set OCR_ENTRY_POLICY=required
set ALLOW_ENTRY_ON_OCR_MISMATCH=false
set OCR_EXIT_POLICY=required
set STRICT_OCR_BEFORE_GATE=true
set ALLOW_EXIT_ON_OCR_FAILED=false
set ALLOW_EXIT_ON_OCR_MISMATCH=false
set ALLOW_EXIT_ON_OCR_FUZZY_MATCH=true
set OCR_FUZZY_MAX_DISTANCE=2

set CAMERA_BRIDGE_MODE=full
set ACCESS_GATE_DIRECTION=auto
set VEHICLE_CENTER_DELAY_SEC=0.2
set BURST_COUNT=2
set BURST_INTERVAL_SEC=0.1
set ESP32_CAM_CONNECT_TIMEOUT=1.0
set ESP32_CAM_READ_TIMEOUT=3.5
set PLATE_DETECTOR_MODEL=%BACKEND_DIR%\models\license_plate_detector.pt
set PLATE_DETECTOR_CONF=0.20
set PLATE_DETECTOR_IMGSZ=960
set MAX_PLATE_DETECTIONS_PER_IMAGE=3
set PLATE_CROP_PADDING_RATIO=0.20
set PLATE_DETECTOR_REQUIRED=true
set PLATE_DETECTOR_FALLBACK_FULL_IMAGE=false
set PLATE_DETECTOR_ROI_ENABLED=false
set PLATE_DETECTOR_ROI_X1=0.18
set PLATE_DETECTOR_ROI_Y1=0.12
set PLATE_DETECTOR_ROI_X2=0.82
set PLATE_DETECTOR_ROI_Y2=0.70
set PADDLEOCR_LANG=en
set PADDLEOCR_USE_GPU=false
set OCR_TIMEOUT_SEC=3.5
set OCR_MAX_IMAGES=2
set OCR_SAVE_DEBUG_CROPS=true
set OCR_DEBUG_DIR=%BACKEND_DIR%\captured_images\_ocr_debug
set YOLO_SAVE_DEBUG_IMAGES=true
set YOLO_DEBUG_DIR=%BACKEND_DIR%\captured_images\_yolo_debug
set CAMERA_BRIDGE_SLA_SEC=10
set BACKEND_SLA_RESERVE_SEC=1.0
set ADAPTIVE_THIRD_FRAME=false
set ADAPTIVE_MAX_BURST_COUNT=2
set UPLOAD_SELECTED_FRAMES_ONLY=true
set OCR_FAST_VARIANTS=true
set OCR_MAX_VARIANTS_PER_CROP=3
set REGISTRATION_MODE_CHECK_TIMEOUT=0.6
set OCR_MIN_RETURN_CONFIDENCE=0.15
set STORE_CAPTURED_IMAGES_IN_DB=false
set CAMERA_BRIDGE_DIRECT_DB_VALIDATION=false
set BACKEND_API_BASE_URL=http://localhost:8000/api/v1
rem ESP32_CAM_URL is loaded from backend_v3\.env unless set in this terminal.

if "%ESP32_CAM_URL%"=="http://<IP_ESP32_CAM>/capture" (
    echo.
    echo ERROR: Set ESP32_CAM_URL to the real ESP32-CAM capture URL first.
    echo Example: set ESP32_CAM_URL=http://192.168.1.50/capture
    pause
    exit /b 1
)

start "Smart Parking API V3 - Production" cmd /k "cd /d ""%BACKEND_DIR%"" && set ENABLE_DEV_ACCESS_TOOLS=%ENABLE_DEV_ACCESS_TOOLS%&& set OCR_ENTRY_POLICY=%OCR_ENTRY_POLICY%&& set ALLOW_ENTRY_ON_OCR_MISMATCH=%ALLOW_ENTRY_ON_OCR_MISMATCH%&& set OCR_EXIT_POLICY=%OCR_EXIT_POLICY%&& set STRICT_OCR_BEFORE_GATE=%STRICT_OCR_BEFORE_GATE%&& set ALLOW_EXIT_ON_OCR_FAILED=%ALLOW_EXIT_ON_OCR_FAILED%&& set ALLOW_EXIT_ON_OCR_MISMATCH=%ALLOW_EXIT_ON_OCR_MISMATCH%&& set ALLOW_EXIT_ON_OCR_FUZZY_MATCH=%ALLOW_EXIT_ON_OCR_FUZZY_MATCH%&& set OCR_FUZZY_MAX_DISTANCE=%OCR_FUZZY_MAX_DISTANCE%&& ""%PYTHON_EXE%"" -m app.main"
timeout /t 5 /nobreak >nul
start "Camera Bridge - Production" cmd /k "cd /d ""%BACKEND_DIR%"" && set CAMERA_BRIDGE_MODE=%CAMERA_BRIDGE_MODE%&& set ACCESS_GATE_DIRECTION=%ACCESS_GATE_DIRECTION%&& set VEHICLE_CENTER_DELAY_SEC=%VEHICLE_CENTER_DELAY_SEC%&& set BURST_COUNT=%BURST_COUNT%&& set BURST_INTERVAL_SEC=%BURST_INTERVAL_SEC%&& set ESP32_CAM_CONNECT_TIMEOUT=%ESP32_CAM_CONNECT_TIMEOUT%&& set ESP32_CAM_READ_TIMEOUT=%ESP32_CAM_READ_TIMEOUT%&& set PLATE_DETECTOR_MODEL=%PLATE_DETECTOR_MODEL%&& set PLATE_DETECTOR_CONF=%PLATE_DETECTOR_CONF%&& set PLATE_DETECTOR_IMGSZ=%PLATE_DETECTOR_IMGSZ%&& set MAX_PLATE_DETECTIONS_PER_IMAGE=%MAX_PLATE_DETECTIONS_PER_IMAGE%&& set PLATE_CROP_PADDING_RATIO=%PLATE_CROP_PADDING_RATIO%&& set PLATE_DETECTOR_REQUIRED=%PLATE_DETECTOR_REQUIRED%&& set PLATE_DETECTOR_FALLBACK_FULL_IMAGE=%PLATE_DETECTOR_FALLBACK_FULL_IMAGE%&& set PLATE_DETECTOR_ROI_ENABLED=%PLATE_DETECTOR_ROI_ENABLED%&& set PLATE_DETECTOR_ROI_X1=%PLATE_DETECTOR_ROI_X1%&& set PLATE_DETECTOR_ROI_Y1=%PLATE_DETECTOR_ROI_Y1%&& set PLATE_DETECTOR_ROI_X2=%PLATE_DETECTOR_ROI_X2%&& set PLATE_DETECTOR_ROI_Y2=%PLATE_DETECTOR_ROI_Y2%&& set YOLO_SAVE_DEBUG_IMAGES=%YOLO_SAVE_DEBUG_IMAGES%&& set YOLO_DEBUG_DIR=%YOLO_DEBUG_DIR%&& set PADDLEOCR_LANG=%PADDLEOCR_LANG%&& set PADDLEOCR_USE_GPU=%PADDLEOCR_USE_GPU%&& set OCR_TIMEOUT_SEC=%OCR_TIMEOUT_SEC%&& set OCR_MAX_IMAGES=%OCR_MAX_IMAGES%&& set OCR_SAVE_DEBUG_CROPS=%OCR_SAVE_DEBUG_CROPS%&& set OCR_DEBUG_DIR=%OCR_DEBUG_DIR%&& set OCR_MIN_RETURN_CONFIDENCE=%OCR_MIN_RETURN_CONFIDENCE%&& set STORE_CAPTURED_IMAGES_IN_DB=%STORE_CAPTURED_IMAGES_IN_DB%&& set CAMERA_BRIDGE_DIRECT_DB_VALIDATION=%CAMERA_BRIDGE_DIRECT_DB_VALIDATION%&& set BACKEND_API_BASE_URL=%BACKEND_API_BASE_URL%&& ""%PYTHON_EXE%"" camera_bridge.py"

if exist "%FRONTEND_INDEX%" (
    start "" "%FRONTEND_INDEX%"
)

echo.
echo Smart Parking production mode started.
echo Backend:  http://localhost:8000
echo Events:   http://localhost:8000/api/v1/access-events/events
echo Sessions: http://localhost:8000/api/v1/sessions?status=active
echo Mode:     %CAMERA_BRIDGE_MODE% / %ACCESS_GATE_DIRECTION%
echo Detector: %PLATE_DETECTOR_MODEL% conf=%PLATE_DETECTOR_CONF% imgsz=%PLATE_DETECTOR_IMGSZ% padding=%PLATE_CROP_PADDING_RATIO%
echo YOLO input: full image detection enabled. ROI enabled=%PLATE_DETECTOR_ROI_ENABLED% roi=(%PLATE_DETECTOR_ROI_X1%,%PLATE_DETECTOR_ROI_Y1%,%PLATE_DETECTOR_ROI_X2%,%PLATE_DETECTOR_ROI_Y2%)
echo Debug crops: %OCR_SAVE_DEBUG_CROPS% dir=%OCR_DEBUG_DIR%
echo YOLO debug: %YOLO_SAVE_DEBUG_IMAGES% dir=%YOLO_DEBUG_DIR%
echo Camera:   burst=%BURST_COUNT% interval=%BURST_INTERVAL_SEC%s ocr_images=%OCR_MAX_IMAGES% timeout=%OCR_TIMEOUT_SEC%s
echo Timeout:  connect=%ESP32_CAM_CONNECT_TIMEOUT%s read=%ESP32_CAM_READ_TIMEOUT%s
echo SLA:      %CAMERA_BRIDGE_SLA_SEC%s backend_reserve=%BACKEND_SLA_RESERVE_SEC%s adaptive_third=%ADAPTIVE_THIRD_FRAME% upload_selected=%UPLOAD_SELECTED_FRAMES_ONLY% fast_variants=%OCR_FAST_VARIANTS%
if "%ESP32_CAM_URL%"=="" (
    echo ESP32-CAM: backend_v3\.env
) else (
    echo ESP32-CAM: %ESP32_CAM_URL%
)
echo.
echo Production policy: entry/exit require OCR, dev reset tools disabled.
echo.
pause
