@echo off
setlocal

set ROOT_DIR=%~dp0..
set BACKEND_DIR=%ROOT_DIR%\backend_v3
set FRONTEND_INDEX=%ROOT_DIR%\frontend_v3\index.html

set PYTHON_EXE=python
if exist "%BACKEND_DIR%\.venv-py312\Scripts\python.exe" (
    set PYTHON_EXE=%BACKEND_DIR%\.venv-py312\Scripts\python.exe
)

set ENABLE_DEV_ACCESS_TOOLS=false
set OCR_ENTRY_POLICY=optional
set ALLOW_ENTRY_ON_OCR_MISMATCH=false
set OCR_EXIT_POLICY=required
set ALLOW_EXIT_ON_OCR_FAILED=false
set ALLOW_EXIT_ON_OCR_MISMATCH=false
set ALLOW_EXIT_ON_OCR_FUZZY_MATCH=true
set OCR_FUZZY_MAX_DISTANCE=2

set CAMERA_BRIDGE_MODE=full
set ACCESS_GATE_DIRECTION=auto
set PLATE_DETECTOR_MODEL=%BACKEND_DIR%\models\license_plate_detector.pt
set PLATE_DETECTOR_CONF=0.35
set PLATE_DETECTOR_REQUIRED=true
set PLATE_DETECTOR_FALLBACK_FULL_IMAGE=false
set PADDLEOCR_LANG=en
set PADDLEOCR_USE_GPU=false
set OCR_TIMEOUT_SEC=10
set OCR_MIN_RETURN_CONFIDENCE=0.15
set STORE_CAPTURED_IMAGES_IN_DB=false
set CAMERA_BRIDGE_DIRECT_DB_VALIDATION=false
set BACKEND_API_BASE_URL=http://localhost:8000/api/v1

start "Smart Parking API V3 - Production" cmd /k "cd /d ""%BACKEND_DIR%"" && set ENABLE_DEV_ACCESS_TOOLS=%ENABLE_DEV_ACCESS_TOOLS%&& set OCR_ENTRY_POLICY=%OCR_ENTRY_POLICY%&& set ALLOW_ENTRY_ON_OCR_MISMATCH=%ALLOW_ENTRY_ON_OCR_MISMATCH%&& set OCR_EXIT_POLICY=%OCR_EXIT_POLICY%&& set ALLOW_EXIT_ON_OCR_FAILED=%ALLOW_EXIT_ON_OCR_FAILED%&& set ALLOW_EXIT_ON_OCR_MISMATCH=%ALLOW_EXIT_ON_OCR_MISMATCH%&& set ALLOW_EXIT_ON_OCR_FUZZY_MATCH=%ALLOW_EXIT_ON_OCR_FUZZY_MATCH%&& set OCR_FUZZY_MAX_DISTANCE=%OCR_FUZZY_MAX_DISTANCE%&& ""%PYTHON_EXE%"" -m app.main"
timeout /t 5 /nobreak >nul
start "Camera Bridge - Production" cmd /k "cd /d ""%BACKEND_DIR%"" && set CAMERA_BRIDGE_MODE=%CAMERA_BRIDGE_MODE%&& set ACCESS_GATE_DIRECTION=%ACCESS_GATE_DIRECTION%&& set PLATE_DETECTOR_MODEL=%PLATE_DETECTOR_MODEL%&& set PLATE_DETECTOR_CONF=%PLATE_DETECTOR_CONF%&& set PLATE_DETECTOR_REQUIRED=%PLATE_DETECTOR_REQUIRED%&& set PLATE_DETECTOR_FALLBACK_FULL_IMAGE=%PLATE_DETECTOR_FALLBACK_FULL_IMAGE%&& set PADDLEOCR_LANG=%PADDLEOCR_LANG%&& set PADDLEOCR_USE_GPU=%PADDLEOCR_USE_GPU%&& set OCR_TIMEOUT_SEC=%OCR_TIMEOUT_SEC%&& set OCR_MIN_RETURN_CONFIDENCE=%OCR_MIN_RETURN_CONFIDENCE%&& set STORE_CAPTURED_IMAGES_IN_DB=%STORE_CAPTURED_IMAGES_IN_DB%&& set CAMERA_BRIDGE_DIRECT_DB_VALIDATION=%CAMERA_BRIDGE_DIRECT_DB_VALIDATION%&& set BACKEND_API_BASE_URL=%BACKEND_API_BASE_URL%&& ""%PYTHON_EXE%"" camera_bridge.py"

if exist "%FRONTEND_INDEX%" (
    start "" "%FRONTEND_INDEX%"
)

echo.
echo Smart Parking production mode started.
echo Backend:  http://localhost:8000
echo Events:   http://localhost:8000/api/v1/access-events/events
echo Sessions: http://localhost:8000/api/v1/sessions?status=active
echo Mode:     %CAMERA_BRIDGE_MODE% / %ACCESS_GATE_DIRECTION%
echo.
echo Production policy: exit requires OCR, dev reset tools disabled.
echo.
pause
