"""
Example ESP32 RFID/barrier config for offline demo.
Copy values into esp32_config.py before uploading firmware to ESP32.
"""

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASS = "YOUR_WIFI_PASSWORD"
WIFI_TIMEOUT = 20
WIFI_RETRY_DELAY = 5

# Legacy HTTP firmware only. Current main.py uses MQTT.
API_BASE_URL = "http://IP_MAY_TINH_CHAY_BACKEND:8000/api/v1"
API_TIMEOUT = 10
API_RETRY = 3

# MQTT local broker running on the demo laptop/PC.
MQTT_BROKER = "IP_MAY_TINH_CHAY_MOSQUITTO"
MQTT_PORT = 1883
MQTT_KEEPALIVE = 60
MQTT_CLIENT_ID = "esp32-gate-01"
MQTT_TOPIC_RFID = "pbl5/smartparking/rfid_scanned"
MQTT_TOPIC_GATE = "pbl5/smartparking/gate"
MQTT_TOPIC_GATE_ACK = "pbl5/smartparking/gate_ack"
MQTT_TOPIC_PARKING_STATUS = "pbl5/smartparking/parking_status"
MQTT_RECONNECT_DELAY = 5

GATE_ID = 1
GATE_NAME = "Cong chinh"
GATE_OPEN_DURATION = 5
GATE_AUTO_CLOSE = True

RFID_SCK_PIN = 18
RFID_MOSI_PIN = 23
RFID_MISO_PIN = 19
RFID_CS_PIN = 5
RFID_RST_PIN = 4
RFID_SPI_BAUDRATE = 1_000_000

SERVO_ENTRY_PIN = 14
SERVO_EXIT_PIN = 27
SERVO_PIN = SERVO_ENTRY_PIN
SERVO_FREQ = 50
SERVO_ANGLE_OPEN = 0
SERVO_ANGLE_CLOSE = 90
SERVO_ENTRY_ANGLE_OPEN = SERVO_ANGLE_OPEN
SERVO_ENTRY_ANGLE_CLOSE = SERVO_ANGLE_CLOSE
SERVO_EXIT_ANGLE_OPEN = SERVO_ANGLE_OPEN
SERVO_EXIT_ANGLE_CLOSE = SERVO_ANGLE_CLOSE

LED_PIN = 2
BUZZER_PIN = 13

ULTRASONIC_TRIG_PIN = 26
ULTRASONIC_ECHO_PIN = 35
ULTRASONIC_THRESHOLD_CM = 10

LCD_I2C_ADDR = 0x27
LCD_SDA_PIN = 21
LCD_SCL_PIN = 22
LCD_COLS = 16
LCD_ROWS = 2

SCAN_COOLDOWN_MS = 3000
SCAN_RETRY_ON_ERROR = True

MSG_WELCOME = ">>> READY <<<"
MSG_SCAN_CARD = "Scan RFID Card"
MSG_CONNECTING = "Connecting..."
MSG_WIFI_OK = "WiFi Connected"
MSG_WIFI_FAIL = "WiFi Failed"
MSG_SCANNING = "SCANNING..."
MSG_ACCEPTED = "WELCOME!"
MSG_DENIED = "ACCESS DENIED"
MSG_ERROR = "ERROR"
MSG_OFFLINE = "OFFLINE MODE"

BEEP_SUCCESS_FREQ = 1500
BEEP_SUCCESS_DURATION = 100
BEEP_ERROR_FREQ = 400
BEEP_ERROR_DURATION = 600

DEBUG_MODE = True
DEBUG_SHOW_WIFI_INFO = True
DEBUG_SHOW_API_REQUEST = True
DEBUG_SHOW_RFID_UID = True

OFFLINE_MODE_ENABLED = True
OFFLINE_ALLOW_ALL_CARDS = False
OFFLINE_AUTHORIZED_CARDS = []


def get_api_endpoint(endpoint):
    return f"{API_BASE_URL}{endpoint}"


def is_debug():
    return DEBUG_MODE


def log(message):
    if DEBUG_MODE:
        print(message)
